### ISSUE TITLE
Semantics of "l" vs "L" for liter.

### ISSUE THREAD

**Issue by garretwilson** [jmandel/ucum.js#9]
In reviewing the UCUM I realize that it provides, in case-sensitive mode, two separate units for "liter": one represented by `l` and another represented by `L`. There is no indication that these should be considered semantically interchangeable, and I've been told by someone who has worked with units of measure standards that they represent two separate units in the UCUM view of the world.

Does your library consider `l` and `L` to be synonyms, or to be two distinct units? And in your opinion is your treatment consistent with the UCUM specification?

**Comment by jmandel** [comment]
Hi @garretwilson! Thanks for the question. As you may be able to see from the commit history on this project, I haven't made code changes over the past 2+y, so I don't immediately know the answer to your question. Have you conducted an experiment to see what happens?

**Comment by garretwilson** [comment]
I haven't tried your library at all, yet; I'm evaluating libraries, and indeed evaluating the use of UCUM itself.

So before diving in, my question for you (as you implemented this library and suppose it to be UCUM-compliant), what is your understanding of the UCUM specification --- that is, how your library is _supposed_ to work? If I parse "123mL" and "123ml", would you expect these two quantities, according to the UCUM, to indicate the same quantity in the same units? Or would you expect them to have different units, but when compared indicate that they referred to the same physical amount?

**Comment by jmandel** [comment]
Here's a quick test that demonstrates the behavior (they are indeed equivalent): https://runkit.com/58c1ce626c0f8c0014b2c449/58c1ce626c0f8c0014b2c44a

In short:

![image](https://cloud.githubusercontent.com/assets/313089/23772574/6a178c98-04e9-11e7-917c-5df3a36a8b5c.png)

**Comment by garretwilson** [comment]
Thank you, @jmandel . I am investigating further.

First I need to know if your implementation is a case-sensitive UCUM implementation or a case-sensitive implementation, because UCUM has separate liter definitions for case-sensitive and case-insensitive processing. In the case-insensitive version, it converts either to the lowercase form e.g. `123ml`. But the case-sensitive form seems to consider them separate units. See https://github.com/unitsofmeasurement/uom-systems/issues/4#issuecomment-284885795 .

Is your implementation a case-sensitive or case-insensitive UCUM implementation?

**Comment by jmandel** [comment]
Case sensitive. Please give the library a try and explore further if you're interested :) 

The link above lets you check it out in the browser.

**Comment by garretwilson** [comment]
Thank you for your time, and I hope to start using your library soon. Currently I'm implementing the backend; I plan on trying out your implementation when I switch to the front-end.

Unfortunately the UCUM representation of "liter" has left me puzzled. @keilw has told me [elsewhere](https://github.com/unitsofmeasurement/uom-systems/issues/4#issuecomment-284885795) that UCUM treats `l` and `L` as "different distinct units", yet your implementation is treating them as the same. I [asked Stack Overflow for clarification](http://stackoverflow.com/q/42659261/421049) on what the UCUM really means in this area, but I'm being told the question is off-topic. I'll keep digging... (I thought UCUM was supposed to take away these sort of ambiguities.)

**Comment by keilw** [comment]
Yes indeed, see http://unitsofmeasure.org/ucum.html#section-Grammar-of-Units-and-Unit-Terms in the actual UCUM specification. It contains a so-called **variant** which can be either case-sensitive or case-insensitive. And "Table 5: Other units from ISO 1000, ISO 2955, and some from ANSI X3.50."  under http://unitsofmeasure.org/ucum.html#section-Derived-Unit-Atoms shows two `liter` entries (so does the actual XML if you read it)
One prints "l", the other "L". And in the case-sensitive variant they are parsed the same way, but for case-insensitive you only get one (both "l" and "L" give you the "l" liter because there's no distinction possible in this case) It may be the only case with such ambiguity, but in general there's always a case-sensitive and case-insensitive way to handle UCUM units. If you only do one, then strictly speaking it's not fully "UCUM-compatible". http://unitsofmeasure.org/trac/wiki/FunctionalTests contains UCUM Functional Tests (by former UOMo committer Graham Grieve, so I can say UOMo UCUM is compatible and passes all those tests at least while they were still maintained ;-) ) but the tests were last updated 3 years ago, the UCUM spec and XML a bit later. They could still match please check it out if you are interested in full compatibility.

**Comment by jmandel** [comment]
This repository includes a copy of the functional tests you mentioned (in the "vendor" dir) and a test runner at https://github.com/jmandel/ucum.js/blob/master/test/ucum.js .  From these you can get a feel for compatibility.

**Comment by keilw** [comment]
The tests are about the same age as the last update of the UCM standard test themselves. If this library passes them, too, it should be OK.

**Comment by garretwilson** [comment]
@jmandel thanks for the response, but it doesn't clear up my concern. (Perhaps I'm missing something.) Maybe you can help me understand.

From the test you showed me, you 1) canonicalize the two units "mL" and "ml"; and then 2) compare them by stringifying.

1. First of all, what is this "canonicalize" function? I mean, I know from the ucum.js documentation what it purports  to do, but where is such an operation explained in the UCUM? (I'm familiar with Unicode specifications for different normalization levels, for example, but I see nothing of the sort in the UCUM.) More specifically, **where in the UCUM does it say that a "canonicalization" step would convert "mL" to "ml" or vice versa in case-sensitive mode**? If I understand @keilw correctly, there is no such "canonical" equivalence between the two --- they are "different distinct units" as I quote him above.
2. Secondly in unit.js is the only way to compare two units for equivalency to stringify them and compare the resulting strings?

(Note that I have opened [UCUM Trac ticket 195](http://unitsofmeasure.org/trac/ticket/195) in order to hopefully bring further clarity to this issue.)

**Comment by jmandel** [comment]
Hi @garretwilson -- unfortunately I created this as a hobby project and do not have time to provide detailed support or documentation beyond what I produced when first writing the library. The code is available to explore, and I'd certainly be willing to consider a pull request with proposed improvements.

Apologies if this comes across as curt; I wish I had more time to dig in here, but alas I do not.

**Comment by garretwilson** [comment]
No worries, @jmandel --- I can certainly understand the lack of time! I have so many of my own projects I don't know what to do. hehe But I really appreciate your replying with an update. Maybe I'll get a chance to look into it myself. Cheers.

But at the very least it seems to me that this issue is still open; there seems to be a tension, if not outright contradiction, between what "conanicalize" does and @keilw's assertion that the two units are distinct.

**Comment by keilw** [comment]
No worries, especially I can understand that, having a couple of projects I contribute to (being a Maintenance Lead of the JSR 363 standard means we have a certain obligation, but e.g. the mentioned unit system extensions are projects on top not part of the actual JSR) 
As for https://github.com/jmandel/ucum.js/issues/10 I guess anybody with a Track account could help with that including @garretwilson if he wants (I should have one, too but it's been a few years since I last used it)
